### ISSUE TITLE
How to clear all requests?

### ISSUE THREAD

**Issue by digeomel** [patresk/saturn#3]
Hi, this is an extremely useful extension, thank you for that! 😄 👍 

However, I couldn't find a way to clear all requests and start fresh, as in the Chrome network panel.
Did I miss something?

**Comment by patresk** [comment]
Hi @digeomel, I am glad you find the extension useful! 

The functionality you've mentioned is not yet implemented. I might take a look at it (thanks for feedback btw), or feel free to open a PR if you have some free time on your hands. For now, I usually just cmd+opt+j to close/open Dev Tools, that should clear the list.

**Comment by patresk** [comment]
Hey @digeomel , following up here - I've implemented the requested feature in the linked PR. Feel free to review!

**Comment by digeomel** [comment]
@patresk @dwiyatci thank you both! I was going to give it a try myself but I'm not proficient at React, believe it or not we're using GraphQL with Angular and the apollo-angular client. If it works I'd say merge it! 😄 👍 🥇

**Comment by patresk** [comment]
Closing this - it's released in the store - https://chrome.google.com/webstore/detail/saturn/niddeggaegffgancpopjccbmmhpdfflf. Feel free to update and please consider leaving a review, if you'll still find the extension useful. 😃
