### ISSUE TITLE
🍸 Filter by Operation name

### ISSUE THREAD

**Issue by dwiyatci** [patresk/saturn#5]
Hello, @patresk! 👋 😃  First off, thank you so much for your efforts on this Chrome extension. This is the most useful one I could find out there for debugging GraphQL requests.

That said, I'm missing the ability to filter the requests by (operation) name like in the regular "Network" tab. I believe once this "Filter" and "Clear all" (#3) features are implemented, this extension would be perfect to get a very well going. Thanks again! 🙇🏻‍♂️

**Comment by patresk** [comment]
Hey @dwiyatci, thanks so much for the feedback. I've implemented the requested feature in the linked PR, feel free to review!

**Comment by patresk** [comment]
Closing this issue as the solution is released in the store: https://chrome.google.com/webstore/detail/saturn/niddeggaegffgancpopjccbmmhpdfflf 

If you are happy with the result, please consider leaving a review in the store - I believe it will bring more developers to contribute!
